export const categories = [
    'Electronics',
    'Fashion & Apparel',
    'Home & Kitchen',
    'Beauty & Personal Care',
    'Health & Wellness',
    'Sports & Outdoors',
    'Automotive',
    'Books & Stationery',
    'Toys & Games',
    'Baby Products',
    'Groceries & Gourmet',
    'Pet Supplies',
    'Office Supplies',
    'Jewelry & Accessories',
    'Footwear',
    'Tools & Hardware',
    'Furniture & Decor',
    'Mobile Phones & Accessories',
    'Laptops & Computers',
    'Watches & Wearables',
];


export const Subcategories = [
    {
        name: 'Electronics',
        subcategories: [
            'Mobile Phones',
            'Laptops',
            'Tablets',
            'Headphones',
            'Cameras',
            'Smart Watches',
            'Gaming Consoles',
            'Televisions',
            'Accessories',
        ],
    },
    {
        name: 'Fashion & Apparel',
        subcategories: [
            'Men\'s Clothing',
            'Women\'s Clothing',
            'Kids\' Clothing',
            'Shoes',
            'Bags',
            'Watches',
            'Sunglasses',
            'Accessories',
        ],
    },
    {
        name: 'Home & Kitchen',
        subcategories: [
            'Furniture',
            'Cookware',
            'Appliances',
            'Lighting',
            'Storage & Organization',
            'Bedding',
            'Home Decor',
            'Dining & Serveware',
        ],
    },
    {
        name: 'Beauty & Personal Care',
        subcategories: [
            'Makeup',
            'Skin Care',
            'Hair Care',
            'Fragrances',
            'Grooming Tools',
            'Bath & Body',
            'Oral Care',
        ],
    },
    {
        name: 'Health & Wellness',
        subcategories: [
            'Supplements',
            'Fitness Equipment',
            'Personal Care',
            'Wellness Devices',
            'First Aid',
            'Health Monitors',
        ],
    },
    {
        name: 'Sports & Outdoors',
        subcategories: [
            'Gym Equipment',
            'Sportswear',
            'Camping Gear',
            'Cycling',
            'Yoga',
            'Team Sports',
        ],
    },
    {
        name: 'Automotive',
        subcategories: [
            'Car Accessories',
            'Motorbike Accessories',
            'Oils & Fluids',
            'Tools & Equipment',
            'Car Electronics',
        ],
    },
    {
        name: 'Books & Stationery',
        subcategories: [
            'Fiction',
            'Non-Fiction',
            'Educational',
            'Children\'s Books',
            'Notebooks',
            'Art Supplies',
            'Office Stationery',
        ],
    },
    {
        name: 'Toys & Games',
        subcategories: [
            'Action Figures',
            'Educational Toys',
            'Board Games',
            'Puzzles',
            'Remote Control Toys',
            'Outdoor Play',
        ],
    },
    {
        name: 'Baby Products',
        subcategories: [
            'Diapers & Wipes',
            'Feeding & Nursing',
            'Baby Gear',
            'Baby Clothing',
            'Toys',
            'Health & Safety',
        ],
    },
    {
        name: 'Groceries & Gourmet',
        subcategories: [
            'Snacks',
            'Beverages',
            'Staples',
            'Organic Foods',
            'Baking Essentials',
            'Packaged Foods',
        ],
    },
    {
        name: 'Pet Supplies',
        subcategories: [
            'Dog Food',
            'Cat Food',
            'Toys',
            'Health & Grooming',
            'Pet Accessories',
        ],
    },
    {
        name: 'Office Supplies',
        subcategories: [
            'Stationery',
            'Printers & Ink',
            'Office Furniture',
            'Filing Products',
            'Organizers',
        ],
    },
    {
        name: 'Jewelry & Accessories',
        subcategories: [
            'Necklaces',
            'Earrings',
            'Bracelets',
            'Rings',
            'Watches',
            'Hair Accessories',
        ],
    },
    {
        name: 'Footwear',
        subcategories: [
            'Men\'s Footwear',
            'Women\'s Footwear',
            'Kids\' Footwear',
            'Sports Shoes',
            'Sandals & Slippers',
        ],
    },
    {
        name: 'Tools & Hardware',
        subcategories: [
            'Power Tools',
            'Hand Tools',
            'Safety Equipment',
            'Plumbing',
            'Electrical Supplies',
        ],
    },
    {
        name: 'Furniture & Decor',
        subcategories: [
            'Living Room Furniture',
            'Bedroom Furniture',
            'Office Furniture',
            'Wall Decor',
            'Curtains & Blinds',
        ],
    },
    {
        name: 'Mobile Phones & Accessories',
        subcategories: [
            'Smartphones',
            'Phone Cases',
            'Chargers',
            'Screen Protectors',
            'Power Banks',
        ],
    },
    {
        name: 'Laptops & Computers',
        subcategories: [
            'Laptops',
            'Desktops',
            'Computer Accessories',
            'Printers',
            'Monitors',
            'Storage Devices',
        ],
    },
    {
        name: 'Watches & Wearables',
        subcategories: [
            'Men\'s Watches',
            'Women\'s Watches',
            'Smart Watches',
            'Fitness Bands',
        ],
    },
]
